import profileJson from "../../../profiles/gmail-ios/measured-draft-2026-08-16.json" with { type: "json" };
import type { ClientAdapter, ColorTransformProfile } from "./types.ts";

const supportedProperties = new Set([
  "background", "background-blend-mode", "background-clip", "background-color", "background-image", "background-origin",
  "background-position", "background-repeat", "background-size", "border", "border-bottom", "border-bottom-color",
  "border-bottom-left-radius", "border-bottom-right-radius", "border-bottom-style", "border-bottom-width", "border-collapse",
  "border-color", "border-left", "border-left-color", "border-left-style", "border-left-width", "border-radius", "border-right",
  "border-right-color", "border-right-style", "border-right-width", "border-spacing", "border-style", "border-top",
  "border-top-color", "border-top-left-radius", "border-top-right-radius", "border-top-style", "border-top-width", "border-width",
  "box-shadow", "box-sizing", "break-after", "break-before", "break-inside", "caption-side", "clear", "color", "column-count",
  "column-fill", "column-gap", "column-rule", "column-rule-color", "column-rule-style", "column-rule-width", "column-span",
  "column-width", "columns", "direction", "display", "elevation", "empty-cells", "float", "font", "font-family",
  "font-feature-settings", "font-kerning", "font-size", "font-size-adjust", "font-stretch", "font-style", "font-synthesis",
  "font-variant", "font-variant-alternates", "font-variant-caps", "font-variant-east-asian", "font-variant-ligatures",
  "font-variant-numeric", "font-weight", "height", "image-orientation", "image-resolution", "ime-mode", "isolation",
  "layout-flow", "layout-grid", "layout-grid-char", "layout-grid-char-spacing", "layout-grid-line", "layout-grid-mode",
  "layout-grid-type", "letter-spacing", "line-break", "line-height", "list-style", "list-style-position", "list-style-type",
  "margin", "margin-bottom", "margin-left", "margin-right", "margin-top", "marker-offset", "max-height", "max-width",
  "min-height", "min-width", "mix-blend-mode", "object-fit", "object-position", "opacity", "outline", "outline-color",
  "outline-style", "outline-width", "overflow", "overflow-x", "overflow-y", "padding", "padding-bottom", "padding-left",
  "padding-right", "padding-top", "page-break-after", "page-break-before", "page-break-inside", "pause", "pause-after",
  "pause-before", "pitch", "pitch-range", "position", "quotes", "richness", "speak", "speak-header", "speak-numeral",
  "speak-punctuation", "speech-rate", "stress", "table-layout", "text-align", "text-align-last", "text-autospace",
  "text-combine-upright", "text-decoration", "text-decoration-color", "text-decoration-line", "text-decoration-skip",
  "text-decoration-style", "text-emphasis", "text-emphasis-color", "text-emphasis-style", "text-indent", "text-justify",
  "text-kashida-space", "text-orientation", "text-overflow", "text-transform", "text-underline-position", "unicode-bidi",
  "vertical-align", "visibility", "voice-family", "white-space", "width", "word-break", "word-spacing", "word-wrap",
  "writing-mode", "zoom", "z-index", "fill", "stroke",
]);

export const gmailIosAdapter: ClientAdapter = {
  id: "gmail-ios",
  label: "Gmail",
  platform: "iOS",
  lightPreviewTitle: "Gmail light",
  darkPreviewTitle: "Gmail iOS dark simulation",
  lightPassLabel: "GMAIL PASS",
  darkEyebrow: "DEVICE-VALIDATED DRAFT",
  downloadFilename: "gmail-ios-simulated.html",
  supportedProperties,
  supportsCustomProperties: false,
  supportsCssDataUrls: false,
  preserveGradients: true,
  profile: profileJson as unknown as ColorTransformProfile,
};
